---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-dev-pvc
  namespace: minio-dev
spec:
  storageClassName: nfs-qnap-dev
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi